# This is a basic workflow to help you get started with Actions

name: Automatically generate rigs from icub-models urdf

# Controls when the workflow will run
on:
  repository_dispatch:
    types: [repository_trigger]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  generate_rig:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          channels: conda-forge,robotology
          channel-priority: true

      - name: Dependencies
        shell: bash -l {0}
        run: |
          # Workaround for https://github.com/conda-incubator/setup-miniconda/issues/186
          conda config --remove channels defaults
          # Actual dependencies
          mamba install python=3.8 yarp idyntree
          # Install Blender
          sudo apt-get update
          sudo apt-get install blender

      - name: Install icub-models
        run: |
          git clone https://github.com/robotology/icub-models
          cd icub-models
          mkdir build && cd build
          cmake -DCMAKE_INSTALL_PREFIX=/home/runner/install ..
          make install

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Run conversion script
        run: |
          cd ${GITHUB_WORKSPACE}
          export GAZEBO_MODEL_PATH=${GAZEBO_MODEL_PATH}:/home/runner/install/share/iCub/robots:/home/runner/install/share
          export PYTHONPATH=/usr/share/miniconda/envs/test/lib/python3.8/site-packages
          models_list="\"$(echo ${{ github.event.client_payload.models_list }} > temp.tmp && sed -i 's/ /" "/g' temp.tmp && cat temp.tmp)\""
          models_list=( $models_list )
          for _model in "${models_list[@]}"
          do
            echo "For loop!"
            echo $_model
            _version=$(echo $_model | grep -o -P '(?<=iCubGazeboV).*(?=/model)')
            echo $_version
            blender --python-use-system-env -b -P "./script/urdfToBlender.py" -- --urdf_filename /home/runner/install/share/iCub/robots/iCubGazeboV${_version}/model.urdf --blend_filename ./rigs/iCubBlenderV${_version}.blend
          done
          ls -la ./rigs
          git status
