# This is a basic workflow to help you get started with Actions

name: Automatically generate rigs from icub-models urdf

# Controls when the workflow will run
on:
  repository_dispatch:
    types: [repository_trigger]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  generate_rig:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          channels: conda-forge,robotology
          channel-priority: true

      - name: Dependencies
        shell: bash -l {0}
        run: |
          # Workaround for https://github.com/conda-incubator/setup-miniconda/issues/186
          conda config --remove channels defaults
          # Actual dependencies
          mamba install yarp idyntree gazebo-yarp-plugins
          # Install Blender
          sudo apt-get update
          sudo apt-get install blender
          echo "CHECKING 3.7"
          ls /usr/share/miniconda/envs/test/lib/python3.7
          echo "CHECKING 3.8"
          ls /usr/share/miniconda/envs/test/lib/python3.8
          echo "CHECKING 3.9"
          ls /usr/share/miniconda/envs/test/lib/python3.9

      - name: Install icub-models
        run: |
          git clone https://github.com/robotology/icub-models
          cd icub-models
          mkdir build && cd build
          cmake -DCMAKE_INSTALL_PREFIX=/home/runner/install ..
          make install



      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Run conversion script
        run: |
          ls ${GITHUB_WORKSPACE}
          cd ${GITHUB_WORKSPACE}
          export GAZEBO_MODEL_PATH=${GAZEBO_MODEL_PATH}:/home/runner/install/share/iCub/robots
          blender --python-use-system-env -b -P "./script/urdfToBlender.py" -- --urdf_filename foo.urdf --blend_filename ./rigs/bar.blend
          ls
